apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
spec:
  version: 8.7.0
  count: 1
  elasticsearchRef:
    name: es-logging
    namespace: kube-system
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
        ports:
          - port: 5601
            protocol: TCP
            targetPort: 5601
        selector:
          kibana.k8s.elastic.co/name: kibana-logging
    tls:
      selfSignedCertificate:
        disabled: true
