name: Build and Deploy Helm Charts to gh-pages

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: "latest"

      - name: Create release directory
        run: |
          mkdir -p release
          cp README.md ./release/

      - name: Build and Publish Charts
        run: |
          for chart_dir in $(ls -d ./charts/*/); do
            chart_name=$(basename "$chart_dir")
            helm package "$chart_dir" -d "release"
            echo "Packaged $chart_name"
          done
          cd release
          helm repo index .

      - name: Set up Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PA_TOKEN }}
          publish_dir: ./release # Adjust the path to your build folder
          publish_branch: gh-pages
          user_name: ${{ github.actor }}[bot]
          user_email: ${{ github.actor }}[bot]@users.noreply.github.com

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.PA_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
