name: Build and Deploy Helm Charts to gh-pages

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: "latest"

      - name: Build and Publish Charts
        run: |
          for chart_dir in $(find . -type d -name '*-chart'); do
            chart_name=$(basename "$chart_dir")
            helm package "$chart_dir" -d "$GITHUB_WORKSPACE/charts"
            echo "Packaged $chart_name"
          done

      - name: Set up Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Switch to gh-pages Branch
        run: |
          git checkout gh-pages
          git pull origin gh-pages --rebase
          rm -rf *.tgz README.md index.yaml # Remove existing chart packages and other files

      - name: Copy Packaged Charts
        run: |
          cp "$GITHUB_WORKSPACE"/charts/* .
          echo "Copied packaged charts"

      - name: Update Index File
        run: |
          helm repo index .

      - name: Commit and Push Changes to gh-pages
        run: |
          git add .
          git commit -m "Update Helm charts"
          git push origin gh-pages
